/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TException.h"
#import "FATObject.h"

#import "EDAMErrors.h"

@implementation EDAMUserException

+ (NSString *) structName {
  return @"EDAMUserException";
}

+ (NSArray *) structFields {
  return @[
    [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"errorCode"],
    [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"parameter"],
  ];
}

@end

@implementation EDAMSystemException

+ (NSString *) structName {
  return @"EDAMSystemException";
}

+ (NSArray *) structFields {
  return @[
    [FATField fieldWithIndex:1 type:TType_I32 optional:NO name:@"errorCode"],
    [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"message"],
    [FATField fieldWithIndex:3 type:TType_I32 optional:YES name:@"rateLimitDuration"],
  ];
}

@end

@implementation EDAMNotFoundException

+ (NSString *) structName {
  return @"EDAMNotFoundException";
}

+ (NSArray *) structFields {
  return @[
    [FATField fieldWithIndex:1 type:TType_STRING optional:YES name:@"identifier"],
    [FATField fieldWithIndex:2 type:TType_STRING optional:YES name:@"key"],
  ];
}

@end


@implementation ErrorsConstants
@end

