/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TException.h"
#import "FATObject.h"
#import "EDAMTypes.h"
#import "EDAMErrors.h"

@interface EDAMPublicUserInfo : FATObject 
@property (nonatomic, strong) NSNumber * userId; // EDAMUserID
@property (nonatomic, strong) NSString * shardId;
@property (nonatomic, strong) NSNumber * privilege; // int
@property (nonatomic, strong) NSString * username;
@property (nonatomic, strong) NSString * noteStoreUrl;
@property (nonatomic, strong) NSString * webApiUrlPrefix;
@end

@interface EDAMAuthenticationResult : FATObject 
@property (nonatomic, strong) NSNumber * currentTime; // EDAMTimestamp
@property (nonatomic, strong) NSString * authenticationToken;
@property (nonatomic, strong) NSNumber * expiration; // EDAMTimestamp
@property (nonatomic, strong) EDAMUser * user;
@property (nonatomic, strong) EDAMPublicUserInfo * publicUserInfo;
@property (nonatomic, strong) NSString * noteStoreUrl;
@property (nonatomic, strong) NSString * webApiUrlPrefix;
@property (nonatomic, strong) NSNumber * secondFactorRequired; // BOOL
@property (nonatomic, strong) NSString * secondFactorDeliveryHint;
@end

@interface EDAMBootstrapSettings : FATObject 
@property (nonatomic, strong) NSString * serviceHost;
@property (nonatomic, strong) NSString * marketingUrl;
@property (nonatomic, strong) NSString * supportUrl;
@property (nonatomic, strong) NSString * accountEmailDomain;
@property (nonatomic, strong) NSString * cardscanUrl;
@property (nonatomic, strong) NSString * announcementsUrl;
@property (nonatomic, strong) NSNumber * enableFacebookSharing; // BOOL
@property (nonatomic, strong) NSNumber * enableGiftSubscriptions; // BOOL
@property (nonatomic, strong) NSNumber * enableSupportTickets; // BOOL
@property (nonatomic, strong) NSNumber * enableSharedNotebooks; // BOOL
@property (nonatomic, strong) NSNumber * enableSingleNoteSharing; // BOOL
@property (nonatomic, strong) NSNumber * enableSponsoredAccounts; // BOOL
@property (nonatomic, strong) NSNumber * enableTwitterSharing; // BOOL
@property (nonatomic, strong) NSNumber * enableLinkedInSharing; // BOOL
@property (nonatomic, strong) NSNumber * enablePublicNotebooks; // BOOL
@end

@interface EDAMBootstrapProfile : FATObject 
@property (nonatomic, strong) NSString * name;
@property (nonatomic, strong) EDAMBootstrapSettings * settings;
@end

@interface EDAMBootstrapInfo : FATObject 
@property (nonatomic, strong) NSArray * profiles;
@end

@protocol EDAMUserStore <NSObject>
- (BOOL) checkVersion: (NSString *) clientName edamVersionMajor: (int16_t) edamVersionMajor edamVersionMinor: (int16_t) edamVersionMinor;  // throws TException
- (EDAMBootstrapInfo *) getBootstrapInfo: (NSString *) locale;  // throws TException
- (EDAMAuthenticationResult *) authenticate: (NSString *) username password: (NSString *) password consumerKey: (NSString *) consumerKey consumerSecret: (NSString *) consumerSecret supportsTwoFactor: (BOOL) supportsTwoFactor;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMAuthenticationResult *) authenticateLongSession: (NSString *) username password: (NSString *) password consumerKey: (NSString *) consumerKey consumerSecret: (NSString *) consumerSecret deviceIdentifier: (NSString *) deviceIdentifier deviceDescription: (NSString *) deviceDescription supportsTwoFactor: (BOOL) supportsTwoFactor;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMAuthenticationResult *) completeTwoFactorAuthentication: (NSString *) authenticationToken oneTimeCode: (NSString *) oneTimeCode deviceIdentifier: (NSString *) deviceIdentifier deviceDescription: (NSString *) deviceDescription;  // throws EDAMUserException *, EDAMSystemException *, TException
- (void) revokeLongSession: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMAuthenticationResult *) authenticateToBusiness: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMAuthenticationResult *) refreshAuthentication: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMUser *) getUser: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (EDAMPublicUserInfo *) getPublicUserInfo: (NSString *) username;  // throws EDAMNotFoundException *, EDAMSystemException *, EDAMUserException *, TException
- (EDAMPremiumInfo *) getPremiumInfo: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (NSString *) getNoteStoreUrl: (NSString *) authenticationToken;  // throws EDAMUserException *, EDAMSystemException *, TException
- (void) inviteToBusiness: (NSString *) authenticationToken emailAddress: (NSString *) emailAddress;  // throws EDAMUserException *, EDAMSystemException *, TException
- (void) removeFromBusiness: (NSString *) authenticationToken emailAddress: (NSString *) emailAddress;  // throws EDAMUserException *, EDAMSystemException *, EDAMNotFoundException *, TException
@end

@interface EDAMUserStoreClient : NSObject <EDAMUserStore> 
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface EDAMUserStoreConstants : NSObject 
+ (int16_t) EDAM_VERSION_MAJOR;
+ (int16_t) EDAM_VERSION_MINOR;
@end
